### ISSUE TITLE
Jid and Arguments not displaying

### ISSUE THREAD

**Issue by Sayanc93** [utgarda/sidekiq-status#85] opened 2016-06-22 13:53 UTC
<img width="1208" alt="screen shot 2016-06-22 at 7 21 37 pm" src="https://cloud.githubusercontent.com/assets/6565629/16269108/9dca998e-38ae-11e6-9fb6-94cc1c0a275d.png">

our sidekiq.rb looks like this:

``` ruby
require 'sidekiq'
require 'sidekiq-status'
require 'resolv-replace' unless Rails.env.test?

redis = proc { Redis.new(url: RedisUtil.redis_url('', 'sidekiq_db')) }

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 25, &redis)
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 25, &redis)
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end
Sidekiq.default_worker_options = { 'backtrace' => 5, 'retry' => 3 }
```

Also our routes for sidekiq looks like:

``` ruby
require 'sidekiq/web'
require 'sidekiq-status/web'
authenticate :admin do
  mount Sidekiq::Web => '/sidekiq'
end
```

We also added `include Sidekiq::Status::Worker` in job.rb

**Comment by pramodshinde** [comment] 2016-06-26 06:31
@Sayanc93 Can you add your job.rb/worker code & how you are invoking job that will help me to re-produce this issue?

**Comment by ajahongir** [comment] 2016-06-28 14:41
I have same issue. on development mode args and jids was an empty but on production it works well.

**Comment by pramodshinde** [comment] 2016-06-28 14:43
@ajahongir  Can you provide me more details like your job.rb/worker code & how you are invoking job that will help me to re-produce this issue?

**Comment by Sayanc93** [comment] 2016-06-28 15:33
my bad, missed this on my emails.
The code is nothing unusual and is invoked as any other sidekiq job ClassName.perform_async()
and the code has a .each ruby loop and some ruby code.

**Comment by Sayanc93** [comment] 2016-06-28 15:34
I am forking the repo to see if i can figure this out on my own :)

**Comment by ajahongir** [comment] 2016-07-04 11:50
![sidekiq](https://cloud.githubusercontent.com/assets/625014/16559515/f8207c6e-41f5-11e6-9fab-7443d9329539.png)

I am having this issue on production too. as you can see I am running only single worker but with different args. But for some reasong sometimes jid and args not passing.

```ruby
class FlightParserWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker

  def expiration
    @expiration ||= 60*60*24*30 # 30 days
  end

  sidekiq_options queue: :flight_parser, backtrace: true, retry: 3

  def perform(args)
    #some code
  end
end
```

enqueue:
`Sidekiq::Client.enqueue_to(queue, FlightParserWorker, args)`

**Comment by ajahongir** [comment] 2016-07-04 11:51
another behavior that I see. for some reasong "Recent job statuses" logging only when page is active. another time nothing is logging out. is this right behavior?

**Comment by dmitry** [comment] 2016-08-01 14:44
Anyone found the reason of unexpected behaviour?

**Comment by pramodshinde** [comment] 2016-09-11 15:49
@Sayanc93 Any updates on this?

**Comment by IamNaN** [comment] 2016-09-21 21:30
I updated sidekiq from 3.4.1 to 4.2.1 and those fields started displaying for me.

**Comment by dmitry** [comment] 2016-09-21 22:21
@utgarda please can we note that somewhere in the readme?

**Comment by utgarda** [comment] 2016-09-22 11:52
@dmitry Why not, thanks for the hint.

**Comment by alor** [comment] 2016-09-23 20:53
same problem for me. no worker arguments displayed and also the percentage does not update until it's :complete. while :working the percentage is not displayed but if i get it with Sidekiq::Status::get_all the "at" value is reported correctly

**Comment by IamNaN** [comment] 2016-09-23 23:47
It sounds like you don't have the rack middleware set up.

**Comment by alor** [comment] 2016-09-24 13:01
I had previously not configured the middleware and i was not getting even the status column and the 100% on completion, than i inserted the initialization in config/initializer/sidekiq.rb:

```ruby
require 'sidekiq'
require 'sidekiq-status'

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end
```

and now i get the status column and the 100% percentage but only at the end when the status is :complete. the other columns (as reported by others) are not shown and the progress seems to not update during :working status

my setup:
rails (4.2.7.1)
redis (3.3.1)
sidekiq (4.2.1)
sidekiq-status (0.6.0)

my worker is as simple as this:

```ruby
class TestWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
  sidekiq_options retry: false

  def expiration
    @expiration ||= 60*60*24*30 # 30 days
  end

  def perform(*args)
    0.upto(100) do |i|
      at i
      sleep 1
    end
  end
end
```

and i execute it via irb like this:

```
2.3.0 :026 > id = TestWorker.perform_async()
 => "1098145bc776c6eb6ef68d1b" 
2.3.0 :027 > Sidekiq::Status::get_all id
 => {"update_time"=>"1474663316", "status"=>"working", "total"=>"100", "at"=>"3", "message"=>""} 
```

**Comment by alor** [comment] 2016-09-24 13:30
i think i found someghing...

in web.rb at:

```ruby
        jids.each do |jid|
          status = Sidekiq::Status::get_all jid
          next if !status || status.count < 2
          status = add_details_to_status(status)
          @statuses << OpenStruct.new(status)
        end
```

the get_all does not return the jid in the status hash.
i can confirm that in redis the jid is not saved in the hash:

```
127.0.0.1:6379> hgetall sidekiq:status:3c77e50dfa0ba99d08df13b5
 1) "update_time"
 2) "1474722725"
 3) "status"
 4) "working"
 5) "total"
 6) "100"
 7) "at"
 8) "84"
 9) "message"
10) ""
```

and since add_details_to_status() will use status['jid'] the percentage is not displayed since it's nil until 'at' is 100.

i suppose even all the other issues derive from the status['jid'] missing.

i'm not keen to the project (started using it yesterday) so i don't know where this 'jid' should be saved in redis (if it has to) or since it's already in the name of the key it's sufficiend to store it in the status hash after the redis.hgetall

what do you think?

**Comment by IamNaN** [comment] 2016-09-24 15:37
Also you didn't set the "total" value in your worker. It works with "at" to give the progress.

**Comment by alor** [comment] 2016-09-24 19:28
total should be 100 by default. you can omit it.

**Comment by pramodshinde** [comment] 2016-09-27 09:54
I investigated it with both sidekiq versions `3.4.1` and `4.2.1`, With both version I could see all arguments and job info nothing is missing, Here is worker I used to cross-check.
![issue-85](https://cloud.githubusercontent.com/assets/3205383/18868539/3ce48076-84c6-11e6-9272-33333e0003a5.png)

```ruby
class UserWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
  sidekiq_options backtrace: true, retry: 3

  def expiration
    @expiration ||= 60*60*24*30 # 30 days
  end 

  def perform(args)
    #some code
  end 
end
```
@IamNaN was you able to repro this issue with sidekiq `3.4.1`, If yes can post detail steps to repros this I want double sure this is issue with `3.4.1` before adding it to readme.

**Comment by why-el** [comment] 2016-09-30 16:55
@pramodshinde does your reproduction steps include showing a percentage that is not 100% (something in between)? That seems to be the crucial issue here.

**Comment by pramodshinde** [comment] 2016-10-06 09:30
I checked after adding some percentage updated my above template worker to have
```ruby
def perform(args)
  0.upto(100) do |i| 
    at i
    sleep 1
  end 
end 
``` 
I can see all arguments with sidekiq versions `3.4.1` and `4.2.1`
![work-p](https://cloud.githubusercontent.com/assets/3205383/19147331/448586d4-8bd5-11e6-8009-d73c41b43a85.png)
FYI - I am used latest master & version `0.6.0`

**Comment by dmitry** [comment] 2016-10-06 10:47
Looks like this issue could be closed then.

**Comment by why-el** [comment] 2016-10-06 14:56
Great, thanks @pramodshinde. I will try with those versions.

**Comment by pramodshinde** [comment] 2016-10-06 17:17
@dmitry okay once @why-el confirms its working as expected at his end we will close this.

**Comment by matrinox** [comment] 2016-12-14 20:39
In my case it was because `'config/initializers/sidekiq'` was not being loaded. Adding the example code and requiring that file worked after not working like shown here

**Comment by why-el** [comment] 2016-12-14 20:40
@pramodshinde unfortunately we moved on with a custom solution, so I am not sure I have the time to review this.

**Comment by strzibny** [comment] 2017-05-10 12:26
I am seeing something similar now. I created a separated script that does not load and **does not initialize** the Rails app (to reduce RAM):

```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
require 'bundler'
Bundler.setup(:default, :scheduler)

# Require only libs we need
require 'redis'
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq-status'
require 'sidekiq-status/web'
require 'sidekiq-unique-jobs'
require 'rufus-scheduler'
require 'rollbar'
require 'active_support'
require 'active_support/core_ext'
require 'app/workers/worker.rb'

# Does not show up args
Worker.perform_async

# Shows args just fine
Worker.perform_in(1.seconds)
```
If I initialize Rails both works as expected. But I am trying to avoid it so now I am doing the workaround with `.perform_in(1.seconds)`. 

Unfortunately I don't know what's the problem with `perform_async`.

**Comment by Sayanc93** [comment] 2017-09-21 06:07
I think we can close this issue?

**Comment by Sayanc93** [comment] 2017-09-21 06:07
@pramodshinde I think we can close this issue?

**Comment by Sayanc93** [comment] 2017-09-21 06:09
@strzibny I suspect that has something to do with sidekiq's mechanism to trigger background jobs.

**Comment by pramodshinde** [comment] 2017-09-21 11:01
I need check, will check soon

**Comment by kenaniah** [comment] 2017-11-11 22:19
As far as I can tell, this now works on the upcoming 0.7.0 release, so I'm closing this issue for now.

**Closed by kenaniah** 2017-11-11 22:19 UTC
Labels: bug, repro steps needed
